name: Factions
version: 1.4.4
main: com.massivecraft.factions.Factions
softdepend:
  - Permissions
  - Essentials
  - EssentialsChat
  - HeroChat
  - iChat
  - LocalAreaChat
  - iConomy
commands:
  f:
    description: All of the Factions commands
    usage: See documentation.
permissions:
  factions.*:
    description: Grants all Factions permissions
    children:
      factions.participate: true
      factions.create: true
      factions.viewAnyPower: true
      factions.adminBypass: true
      factions.config: true
      factions.disband: true
      factions.lock: true
      factions.manageSafeZone: true
      factions.manageWarZone: true
      factions.ownershipBypass: true
      factions.reload: true
      factions.saveall: true
      factions.commandDisable.none: true
  factions.participate:
    description: Allows the player to participate in a faction
    default: true
  factions.create:
    description: Allows the player to create a new faction
    default: true
  factions.viewAnyPower:
    description: Allows the player to view the power level of anyone else
    default: true
  factions.adminBypass:
    description: Allows the player to bypass many normal restrictions, and use the bypass command
    default: op
  factions.config:
    description: Can use /f config command to change conf.json options
    default: op
  factions.disband:
    description: Can use the /f disband <faction> command to disband any faction
    default: op
  factions.lock:
    description: Can use the /f lock [on/off] command to temporarily lock the data files from being overwritten
    default: op
  factions.manageSafeZone:
    description: Allows the player to claim land as a safe zone, and to build/destroy within safe zones
    default: op
  factions.manageWarZone:
    description: Allows the player to claim land as a war zone, and to build/destroy within war zones
    default: op
  factions.ownershipBypass:
    description: Allows the player to bypass ownership restrictions within own faction's territory
    default: op
  factions.reload:
    description: Can use the /f reload command to reload data file(s) from disk
    default: op
  factions.saveall:
    description: Can use the /f saveall command to save all data to disk
    default: op
  factions.commandDisable.none:
    description: no commands disabled (ignore all other commandDisable permissions)
    default: op
  factions.commandDisable.admin:
    description: admin command disabled
    default: false
  factions.commandDisable.autoclaim:
    description: autoclaim command disabled
    default: false
  factions.commandDisable.autosafe:
    description: autosafe command disabled
    default: false
  factions.commandDisable.autowar:
    description: autowar command disabled
    default: false
  factions.commandDisable.bypass:
    description: bypass command disabled
    default: false
  factions.commandDisable.chat:
    description: chat command disabled
    default: false
  factions.commandDisable.c:
    description: chat command disabled
    default: false
  factions.commandDisable.claim:
    description: claim command disabled
    default: false
  factions.commandDisable.create:
    description: create command disabled
    default: false
  factions.commandDisable.deinvite:
    description: deinvite command disabled
    default: false
  factions.commandDisable.deinv:
    description: deinvite command disabled
    default: false
  factions.commandDisable.desc:
    description: desc command disabled
    default: false
  factions.commandDisable.disband:
    description: disband command disabled
    default: false
  factions.commandDisable.help:
    description: help command disabled
    default: false
  factions.commandDisable.h:
    description: help command disabled
    default: false
  factions.commandDisable.?:
    description: help command disabled
    default: false
  factions.commandDisable.home:
    description: home command disabled
    default: false
  factions.commandDisable.invite:
    description: invite command disabled
    default: false
  factions.commandDisable.inv:
    description: invite command disabled
    default: false
  factions.commandDisable.join:
    description: join command disabled
    default: false
  factions.commandDisable.kick:
    description: kick command disabled
    default: false
  factions.commandDisable.leave:
    description: leave command disabled
    default: false
  factions.commandDisable.list:
    description: list command disabled
    default: false
  factions.commandDisable.ls:
    description: list command disabled
    default: false
  factions.commandDisable.lock:
    description: lock command disabled
    default: false
  factions.commandDisable.map:
    description: map command disabled
    default: false
  factions.commandDisable.mod:
    description: mod command disabled
    default: false
  factions.commandDisable.open:
    description: open command disabled
    default: false
  factions.commandDisable.close:
    description: open command disabled
    default: false
  factions.commandDisable.owner:
    description: owner command disabled
    default: false
  factions.commandDisable.ownerlist:
    description: ownerlist command disabled
    default: false
  factions.commandDisable.power:
    description: power command disabled
    default: false
  factions.commandDisable.pow:
    description: power command disabled
    default: false
  factions.commandDisable.ally:
    description: ally command disabled
    default: false
  factions.commandDisable.enemy:
    description: enemy command disabled
    default: false
  factions.commandDisable.neutral:
    description: neutral command disabled
    default: false
  factions.commandDisable.reload:
    description: reload command disabled
    default: false
  factions.commandDisable.safeclaim:
    description: safeclaim command disabled
    default: false
  factions.commandDisable.safe:
    description: safeclaim command disabled
    default: false
  factions.commandDisable.safeunclaimall:
    description: safeunclaimall command disabled
    default: false
  factions.commandDisable.safedeclaimall:
    description: safeunclaimall command disabled
    default: false
  factions.commandDisable.saveall:
    description: saveall command disabled
    default: false
  factions.commandDisable.save:
    description: saveall command disabled
    default: false
  factions.commandDisable.sethome:
    description: sethome command disabled
    default: false
  factions.commandDisable.show:
    description: show command disabled
    default: false
  factions.commandDisable.who:
    description: show command disabled
    default: false
  factions.commandDisable.tag:
    description: tag command disabled
    default: false
  factions.commandDisable.title:
    description: title command disabled
    default: false
  factions.commandDisable.unclaim:
    description: unclaim command disabled
    default: false
  factions.commandDisable.declaim:
    description: unclaim command disabled
    default: false
  factions.commandDisable.unclaimall:
    description: unclaimall command disabled
    default: false
  factions.commandDisable.declaimall:
    description: unclaimall command disabled
    default: false
  factions.commandDisable.version:
    description: version command disabled
    default: false
  factions.commandDisable.warclaim:
    description: warclaim command disabled
    default: false
  factions.commandDisable.war:
    description: warclaim command disabled
    default: false
  factions.commandDisable.warunclaimall:
    description: warunclaimall command disabled
    default: false
  factions.commandDisable.wardeclaimall:
    description: warunclaimall command disabled
    default: false
  factions.commandDisable.worldnoclaim:
    description: worldnoclaim command disabled
    default: false
  factions.commandDisable.worldnopowerloss:
    description: worldnopowerloss command disabled
    default: false
